# Generated by Django 5.2.1 on 2025-06-20 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='hire_person_type',
            field=models.CharField(choices=[('Employee', 'Employee'), ('Contractor', 'Contractor'), ('Personal Profile', 'Personal Profile')], default='Contractor', max_length=50),
        ),
    ]
