# Generated by Django 5.2.1 on 2025-06-24 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_employee_payment_cycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='last_salary_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='next_salary_date',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.today, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
