# Generated by Django 5.2.1 on 2025-06-24 07:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_payment_last_salary_amount_payment_next_salary_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='last_salary_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='next_salary_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
