# Generated by Django 5.2.1 on 2025-06-24 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_employee_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='next_salary_date',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
