# Generated by Django 5.2.1 on 2025-06-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_payment_next_salary_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
